config/routes.rb
MeuSalao::Application.routes.draw do

  match 'salao' => 'salao#index'
  match 'saloa/pessoa' => 'salao#pessoa'
  match 'pessoa/empresa' => 'pessoa#empresa'
  

end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
  attr_accessible :nome
end

app/models/teste.rb
class Teste < ActiveRecord::Base
  attr_accessible :string
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pessoa_controller.rb
class PessoaController < ApplicationController

  def new
    
  end

  def empresa

    respond_to do |format|
     format.js {render :layout => false} 
    end
    
  end

end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pessoas }
    end
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
    @pessoa = Pessoa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pessoa }
    end
  end

  # GET /pessoas/new
  # GET /pessoas/new.json
  def new
    @pessoa = Pessoa.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pessoa }
    end
  end

  # GET /pessoas/1/edit
  def edit
    @pessoa = Pessoa.find(params[:id])
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(params[:pessoa])

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render json: @pessoa, status: :created, location: @pessoa }
      else
        format.html { render action: "new" }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pessoas/1
  # PUT /pessoas/1.json
  def update
    @pessoa = Pessoa.find(params[:id])

    respond_to do |format|
      if @pessoa.update_attributes(params[:pessoa])
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa = Pessoa.find(params[:id])
    @pessoa.destroy

    respond_to do |format|
      format.html { redirect_to pessoas_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/salao_controller.rb
class SalaoController < ApplicationController

  def index
  
  end

  def pessoa
    @pessoa = Pessoa.last
    respond_to do |format|
format.js 
    end
  end

end

app/controllers/testes_controller.rb
class TestesController < ApplicationController
  # GET /testes
  # GET /testes.json
  def index
    @testes = Teste.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @testes }
    end
  end

  # GET /testes/1
  # GET /testes/1.json
  def show
    @testis = Teste.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @testis }
    end
  end

  # GET /testes/new
  # GET /testes/new.json
  def new
    @testis = Teste.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @testis }
    end
  end

  # GET /testes/1/edit
  def edit
    @testis = Teste.find(params[:id])
  end

  # POST /testes
  # POST /testes.json
  def create
    @testis = Teste.new(params[:testis])

    respond_to do |format|
      if @testis.save
        format.html { redirect_to @testis, notice: 'Teste was successfully created.' }
        format.json { render json: @testis, status: :created, location: @testis }
      else
        format.html { render action: "new" }
        format.json { render json: @testis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /testes/1
  # PUT /testes/1.json
  def update
    @testis = Teste.find(params[:id])

    respond_to do |format|
      if @testis.update_attributes(params[:testis])
        format.html { redirect_to @testis, notice: 'Teste was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @testis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testes/1
  # DELETE /testes/1.json
  def destroy
    @testis = Teste.find(params[:id])
    @testis.destroy

    respond_to do |format|
      format.html { redirect_to testes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/salao_helper.rb
module SalaoHelper
end

app/helpers/testes_helper.rb
module TestesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MeuSalao</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pessoa/_empresa.html.erb
<br />
<b>EMPRESA</b>

<input type="text">
<button>Buscar</button>
<br />
<br />
<table border="1">
  <tr>
    <td><b>Nome</b></td>
    <td><b>Telefone</b></td>
    <td><b>Email</b></td>
    <td><b>Consultar</b></td>
    <td><b>Editar</b></td>
    <td><b>Excluir</b></td>
  </tr>
  <tr>
    <td>Anes Casa da Beleza</td>
    <td>3261-4111</td>
    <td>anes@gmail.com</td>
    <td><button>C</button></td>
    <td><button>E</button></td>
    <td><button>X</button></td>
  </tr>
</table>

app/views/pessoa/empresa.js.erb
$("#painel-lateral-direito").html("<%= escape_javascript( render(:partial => "empresa") ) %>");

app/views/pessoas/_form.html.erb
<%= form_for(@pessoa) do |f| %>
  <% if @pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% @pessoa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing pessoa</h1>

<%= render 'form' %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<h1>Listing pessoas</h1>

<table>
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pessoas.each do |pessoa| %>
  <tr>
    <td><%= pessoa.nome %></td>
    <td><%= link_to 'Show', pessoa %></td>
    <td><%= link_to 'Edit', edit_pessoa_path(pessoa) %></td>
    <td><%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pessoa', new_pessoa_path %>

app/views/pessoas/new.html.erb
<h1>New pessoa</h1>

<%= render 'form' %>

<%= link_to 'Back', pessoas_path %>

app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @pessoa.nome %>
</p>


<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>

app/views/salao/_pessoa.html.erb
<h1>EMPRESA</h2>

<input type="text">
<button>Buscar</button>
<button>Novo</button>
<br />
<br />

<table border="1">
  <tr>
    <td><b>Nome</b></td>
    <td><b>CNPJ</b></td>
    <td><b>Consultar</b></td>
    <td><b>Editar</b></td>
    <td><b>Excluir</b></td>
  </tr>
  <tr>
    <td>Anes Casa da Beleza</td>
    <td>000.000.000.0001/06</td>
    <td><button>C</button></td>
    <td><button>E</button></td>
    <td><button>X</button></td>
  </tr>
</table>

app/views/salao/index.html.erb
<link href="stylesheets/menu_assets/styles.css" rel="stylesheet" type="text/css">

<table width=100% height=450px>
  <tr height=15%>
    <td colspan="3" align='center'><h1>ANES CASA DA BELEZA</h1></td>
  </tr>
  <tr height=70%>
    <td width=14% align='center' valign="top">
      <br />
      <div id='cssmenu'>
        <ul>
           <li class='active '><a href='index.html'><span>Principal</span></a></li>
           <li class='has-sub '><a href='#'><span>Pessoa</span></a>
              <ul>
                 <li>
                    <%=link_to "Empresa", { :controller => "pessoa", :action => "empresa" }, 
                                            :remote => true,
                                            :update => 'painel-lateral-direito' %>
                 </li>
                 <li><a href='#'><span>Cliente</span></a></li>
                 <li><a href='#'><span>Fornecedor</span></a></li>
                 <li><a href='#'><span>Colaborador</span></a></li>
              </ul>
           </li>
           <li class='has-sub '><a href='#'><span>Products</span></a>
              <ul>
                 <li class='has-sub '><a href='#'><span>Product 1</span></a>
                    <ul>
                       <li><a href='#'><span>Sub Item</span></a></li>
                       <li><a href='#'><span>Sub Item</span></a></li>
                    </ul>
                 </li>
                 <li class='has-sub '><a href='#'><span>Product 2</span></a>
                    <ul>
                       <li><a href='#'><span>Sub Item</span></a></li>
                       <li><a href='#'><span>Sub Item</span></a></li>
                    </ul>
                 </li>
              </ul>
           </li>
           <li><a href='#'><span>About</span></a></li>
           <li><a href='#'><span>Contact</span></a></li>
        </ul>
      </div> 
    </td>
    <td width='7%' ></td>
    <td id='painel-lateral-direito' valign="top"></td>
  </tr>
  <tr height=10%>
    <td colspan="2">Rodape</td>
  </tr>
</table>

app/views/salao/pessoa.js.erb
$("#painel-lateral").html("<%= escape_javascript( render(:partial => "pessoa") ) %>");

app/views/testes/_form.html.erb
<%= form_for(@testis) do |f| %>
  <% if @testis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testis.errors.count, "error") %> prohibited this testis from being saved:</h2>

      <ul>
      <% @testis.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testes/edit.html.erb
<h1>Editing testis</h1>

<%= render 'form' %>

<%= link_to 'Show', @testis %> |
<%= link_to 'Back', testes_path %>

app/views/testes/index.html.erb
<h1>Listing testes</h1>

<table>
  <tr>
    <th>String</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @testes.each do |testis| %>
  <tr>
    <td><%= testis.string %></td>
    <td><%= link_to 'Show', testis %></td>
    <td><%= link_to 'Edit', edit_testis_path(testis) %></td>
    <td><%= link_to 'Destroy', testis, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Teste', new_testis_path %>

app/views/testes/new.html.erb
<h1>New testis</h1>

<%= render 'form' %>

<%= link_to 'Back', testes_path %>

app/views/testes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>String:</b>
  <%= @testis.string %>
</p>


<%= link_to 'Edit', edit_testis_path(@testis) %> |
<%= link_to 'Back', testes_path %>